////
Copyright (c) 2023-2026 The Johns Hopkins University Applied Physics
Laboratory LLC.

This file is part of the Bundle Protocol Security Library (BSL).

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

This work was performed for the Jet Propulsion Laboratory, California
Institute of Technology, sponsored by the United States Government under
the prime contract 80NM0018D0004 between the Caltech and NASA under
subcontract 1700763.
////
= Bundle Protocol Security Library (BSL) v2.0 User{nbsp}Guide
:doctype: book
:backend: docbook5
:docinfo: shared
:toc:
:sectnums:
:source-linenums-option:


== Introduction

This User Guide provides an overview of the application programming interface (API) and high-level workflows of the Bundle Protocol Security Library (BSL), which is part of the NASA Advanced Multi-Mission Operations System (AMMOS) suite of tools.

=== Identification

[%header,width=75%,cols=2*]
|===
|Property
|Value

|Configuration ID (CI)
|681.4

|Element
|Systems Engineering Office (SEO)

|Program Set
|Bundle Protocol Security Library (BSL)

|Version
|2.0
|===

=== Scope

This document describes and explains the API and workflows of the BSL.
For technical details about the BSL architecture, installation, upgrade, monitoring, and maintenance see the <<bsl-product-guide>>.
Details about specific API structures and cross-relationships is provided in the online <<bsl-main-api>>.

=== Terminology

The following are Generic terms:

Application Programming Interface (API)::
The programming language-level interface defined by a library.
For the C-language this is defined by header files in a specific directory structure.
Application Binary Interface (ABI)::
A combination of instruction set architecture (ISA) and operating-system-specific binary forms for libraries and executables.
A built library has a specific ABI that can be different on different platforms even if its API does not change.
Concise Binary Object Representation (CBOR)::
A binary encoding defined in <<RFC8949>> which follows a superset of the JSON data model (see below) and enables both small encoded size as well as efficient encoding and decoding.
This is also known as IETF STD 94.
The BSL itself uses CBOR to encode the contents of BPSec ASBs.
CBOR Object Signing and Encryption (COSE)::
A message encoding and processing defined in <<RFC9052>> which uses CBOR as its extensible encoded structure for MAC, Signing, and Encryption operations.
COSE algorithms and header parameters are managed by IANA registries for extensibility.
This is also known as IETF STD 96.
COSE Key and Key Set::
The BSL does not use COSE Keys directly, but the dynamic backend provides an API for loading a COSE Key Set file into a key store and the Mock BPA makes use of this API during its startup.
JavaScript Object Notation (JSON)::
A text encoding defined in <<RFC8259>> which allows a limited data model to be encoded in a human-readable form.
The BSL does not use JSON directly, but the example ION-heritage Policy Provider uses JSON for encoding policy configuration.
JSON Web Key (JWK) and JWK Set::
A JSON data structure defined in <<RFC7517>> which represents a set of cryptographic keys and their parameters.
The BSL does not use JWKs directly, but the dynamic backend provides an API for loading a JWK Set file into a key store and the Mock BPA makes use of this API during its startup.

The following are cryptographic terms (used within security context options and explanations) consistent with NIST <<CSRC>> definitions:

Key Derivation Function (KDF)::
A cryptographic function used to derive symmetric key material from input key material, an entropy-adding "salt" value, and opaque context information data.
One variety of this type of function is a hash-based KDF (HKDF).
Key Derivation Key (KDK)::
A key used as an input to a key-derivation function to derive additional keying material.
Key Encryption Key (KEK)::
A cryptographic key that is used for the encryption or decryption of other keys to provide confidentiality protection for those keys. Also known as a key-wrapping key.
Content Key::
The lowest-layer symmetric key used as input for MAC or AEAD algorithms.
Authenticated Encryption with Associated Data (AEAD)::
A subset of encryption algorithms which outputs an authentication tag along with its ciphertext, and inputs data which is authenticated but not encrypted (AAD).
Initialization Vector (IV)::
An input to authenticated encryption which must be unique for each combination of content key and plaintext.
Additional Authenticated Data (AAD)::
The input data to the authenticated encryption function that is authenticated but not encrypted.
Message Authentication Code (MAC)::
A symmetric key algorithm used to provide integrity over some plaintext, which can itself be composed of a payload along with additional authenticated data.
One variety of this type of function is a hash-based MAC (HMAC).

[#list-terms-bpsec]
The following are BP- and BPSec-related terms:

Bundle Protocol (BP)::
The overlay network protocol used to transport BPSec blocks and target blocks between nodes defined in <<RFC9171>>.
Bundle Protocol Security (BPSec)::
The mandatory-to-implement security mechanism to protect blocks of a BP bundle defined in <<RFC9172>>.
This is the principal scope of behavior implemented in the BSL.
BP Agent (BPA)::
The instantiation of a BP node with a unique administrative Endpoint ID.
A single BPA may have any number of additional endpoints registered to various applications on its node.
BP Endpoint::
The source or destination of a BP bundle, identified by a BP Endpoint ID (EID).
BP Endpoint ID (EID)::
The identifier of a BP Endpoint; names the source and destination for a BP bundle.
Bundle (per BPv7)::
The protocol data unit of Bundle Protocol, which uses a CBOR-encoding of its data.
Block (per BPv7)::
Each sub-element of a bundle.
All bundles contain a mandatory primary block, any number of extension blocks, and a mandatory payload block.
Each extension block has an explicit block type identifier.
Block-Type-Specific Data (BTSD)::
The arbitrary-length binary data containing the contents of a block which is block-type-specific.
Block Integrity Block (BIB)::
A well-known block type used for integrity operations in BPSec.
Block Confidentiality Block (BCB)::
A well-known block type used for integrity operations in BPSec.
Abstract Security Block (ASB)::
A the block-type-specific data for one of the security block types: BIB or BCB, which contains an encoded CBOR sequence.
Security Operation (per BPSec)::
A single security operation is a combination of choosing a type of security (integrity or confidentiality), a single role, a single target (block), a single security context, and a set of options that are context-specific.
Role (per BPSec)::
This determines the action of a security operation, as one of:
Source::: This role causes a security operation to be added to a security block.
Verifier::: This role verifies, but does not modify, a security operation within a security block.
Acceptor::: This role verifies and then removes a security operation within a security block.
Security Context (per BPSec)::
Each security operation has a single associated BPSec context, identified by its Context ID.
Context IDs can either be well-known, and registered with IANA, or taken from a reserved block for private or experimental use.
Target (per BPSec)::
Each security operation has a single target block identified by its unique-to-the-bundle block number.
Parameter (per BPSec)::
Each security block (the entire ASB) has a set of parameters which apply to all operations in the block.
Result (per BPSec)::
Each target of a security block has a set of results which apply to a single operation associated with one target.

[#list-terms-bsl]
The following are BSL-specific terms:

BSL Context::
An container of state and memory allocation for each instance of the BSL.
Each BSL context is not thread safe, it must be used within a single thread exclusively.
Bundle Context::
A container of state and memory allocation for each bundle being processed by a BSL Context.
Policy Provider (PP)::
An abstract interface (and a C callback descriptor struct) for providing security policy to a BSL Context.
The BSL dynamic backend contains a run-time-variable PP registry.
Security Context (SC)::
An abstract interface (and a C callback descriptor struct) for providing BPSec security context processing to a BSL Context.
The BSL dynamic backend contains a run-time-variable SC registry.
Security Action::
Each action contains an ordered sequence of security operations and their internal configuration.
PPs produce sets of actions when inspecting a bundle and operate on the same set of actions when finalizing a bundle.
Security Option::
An option is an internal-to-BSL item which communicates intent for a single Security Operation between PP and SC.


=== References

.Applicable JPL Rules Documents
[%header,cols="<.<3,>.<1"]
|===
|Title
|Document Number

|[[jpl-sd,JPL SD]]Software Development
|57653 rev 10

|===


.Applicable MGSS Documents
[%header,cols="<.<3,>.<1"]
|===
|Title
|Document Number

|[[mimtar,MIMTaR]]MGSS Implementation and Maintenance Task Requirements (MIMTaR)
|DOC-001455 rev I

|[[bsl-srd,BSL SRD]]BSL Software Requirements Document (SRD)
|https://github.com/NASA-AMMOS/BSL-docs/blob/main/BSL%20Software%20Requirements%20Document.pdf[DOC-005735]

|[[bsl-sis,BSL SIS]]BSL Software Interface Specification (SIS)
|https://nasa-ammos.github.io/BSL/html/bsl-sis.html[DOC-005835]

|[[bsl-product-guide,BSL Product Guide]]BSL v2.0 Product Guide
|https://nasa-ammos.github.io/BSL-docs/product-guide/bsl-product-guide.pdf[DOC-005921]

|===

.Applicable Other Documents
[%header,cols="<.<3,>.<1"]
|===
|Title
|Reference

|[[bsl-source]]BSL Source
|https://github.com/NASA-AMMOS/BSL[GitHub project BSL]

|[[bsl-docs]]BSL Documentation Source
|https://github.com/NASA-AMMOS/BSL-docs[GitHub project BSL-docs]

|[[bsl-main-api,BSL API Docs]]BSL API Documentation -- Main Branch
|https://nasa-ammos.github.io/BSL/html/[GitHub Pages for BSL]

|[[C99]]Programming Languages -- C
|https://www.iso.org/standard/29237.html[ISO/IEC 9899:1999]

|[[POSIX]]IEEE Standard for Information Technology - Portable Operating System Interface (POSIX(R))
|https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/[IEEE Std 1003.1-2008]

|[[CSRC,CSRC Glossary]]US NIST Computer Security Resource Center Glossary
|https://csrc.nist.gov/glossary

|[[MLIB]]M*LIB: Generic type-safe Container Library for C language
|https://github.com/P-p-H-d/mlib[GitHub project for M*LIB]

|[[QCBOR]]QCBOR Library
|https://github.com/laurencelundblade/QCBOR[GitHub project for QCBOR]

|[[OpenSSL]]OpenSSL Library
|https://openssl-library.org/[OpenSSL Project]

|[[Jansson]]Jansson Library
|https://github.com/akheron/jansson[GitHub project for Jansson]

|[[unity-test]]Unity Test Library
|https://github.com/ThrowTheSwitch/Unity[GitHub project Unity]

|[[NASA-ION]]NASA Interplanetary Overlay Networking (ION) software
|https://github.com/nasa-jpl/ION-DTN/[GitHub project for ION-DTN]

|[[ION-BPSec-Policy-Manual]]Bundle Protocol Security (BPSec) Policy Configuration for ION Open Source (ION-IOS)
|https://github.com/nasa-jpl/ION-DTN/blob/current/Security_Policy_User_Manual.docx[ION BPSec Policy Manual]

|[[wireshark]]Wireshark Project
|https://www.wireshark.org/

|[[RFC7517]]JSON Web Key (JWK)
|https://www.rfc-editor.org/info/rfc7517[IETF RFC 7517]

|[[RFC8259]]The JavaScript Object Notation (JSON) Data Interchange Format
|https://www.rfc-editor.org/info/rfc8259[IETF RFC 8259]

|[[RFC8949]]Concise Binary Object Representation (CBOR)
|https://www.rfc-editor.org/info/rfc8949[IETF RFC 8949]

|[[RFC9052]]CBOR Object Signing and Encryption (COSE): Structures and Process
|https://www.rfc-editor.org/info/rfc9052[IETF RFC 9052]

|[[RFC9171]]Bundle Protocol Version 7
|https://www.rfc-editor.org/info/rfc9171[IETF RFC 9171]

|[[RFC9172]]Bundle Protocol Security (BPSec)
|https://www.rfc-editor.org/info/rfc9172[IETF RFC 9172]

|[[RFC9173]]Default Security Contexts for Bundle Protocol Security (BPSec)
|https://www.rfc-editor.org/info/rfc9173[IETF RFC 9173]

|[[draft-ietf-dtn-bpsec-cose]]Bundle Protocol Security (BPSec) COSE Context
|https://datatracker.ietf.org/doc/draft-ietf-dtn-bpsec-cose/[draft-ietf-dtn-bpsec-cose]

|[[json-schema]]JSON Schema: A Media Type for Describing JSON Documents
|https://json-schema.org/draft/2020-12/[json-schema-2020-12]

|===


[#sec-arch]
== Architecture

The BSL is a set of software libraries and plugin modules which together perform the functions required by Bundle Protocol Security (BPSec) <<RFC9172>> in a way which can be instantiated from and used by a Bundle Protocol Agent (BPA) operating according to the BPv7 specification <<RFC9171>>.
The BSL comes with an implementation of the BPSec Default Security Contexts <<RFC9173>> and COSE Context <<draft-ietf-dtn-bpsec-cose>>, as well as a sample policy provider which uses JSON configuration inputs with heritage from and limited backward compatibility with ION.

The BSL is made to interact with its environment (BPA, libraries, host OS, _etc._) through function calls into and out of the BSL library based on a <<C99>> Application Programming Interface (API) from header declarations and corresponding Application Binary Interface (ABI) for compiled libraries.

=== Factory Default Configuration

The "factory default" BSL is configured to operate with a dynamic backend which uses dynamic heap allocation and variable-sized data containers (arrays, lists, maps, _etc._).
An alternative backend could be developed for specific BPA needs, but that is outside the scope of the BSL project.

The factory default BSL also builds a sample Policy Provider and example Security Contexts in order to be able to fully exercise the BSL behaviors.
Alternative Policy Providers are expected to be developed and tailored for each BPA integration.
Alternative Security Context implementations are expected to be developed for future contexts, and to adapt to deployment-specific needs such as for key management or specialized cryptographic interfaces.

=== Library Associations

The BSL project is based on a single source tree but is subdivided into separate libraries, each with their own cross-dependencies (for compiling and linking).
The dependencies between areas are shown in <<fig-deps-logical>>, where the single "BSL" block is meant to represent both the frontend and backend libraries for simplicity.

[#fig-deps-logical]
.Logical Structure and Dependencies
[graphviz,format=svg,width=80mm]
----
digraph figure {
    rankdir=TB;
    node [shape=box, fontname=Helvetica, fontsize=12];

    bpa [ label="BP Agent" ];
    bsl [ label="BSL\n(frontend+backend)" ];
    pp [ label="Policy Provider(s)" ];
    sc [ label="Security Context(s)" ];
    crypto [ label="Crypto Provider" ];
    { rank=same; pp; sc; }

    bpa -> bsl [ label="BSL Service API" ];
    bsl -> pp [ label="PP Register"; dir=back; ]
    bsl -> sc [ label="SC Register"; dir=back; ]
    pp -> sc [ label="Options" ];
    sc -> crypto;
}
----

The BSL is internally separated into two layers of implementation: an API-centric abstract Frontend library and a host-binding concrete Backend library.

The Frontend library provides the service API for the BSL to be called by its associated BPA as needed and for stable public APIs used by Policy Provider implementations and Security Context implementations.
The Backend library implements forward-declared structs and functions from the Frontend using specific concrete data containers, algorithms, _etc._

=== BPA Interaction Points

Most interactions with the BSL/frontend API occur within the context of a single bundle.
There are four points along bundle traversal where BSL interaction from the BPA is necessary:

. After bundle **transmission** from an application source (APPIN).
. Before bundle **delivery** to an application destination (APPOUT).
. After bundle **reception** via a CLA (CLIN).
. Before bundle **forwarding** via a CLA (CLOUT).

This is depicted in <<fig-bsl-interaction-points>>, where each of the edges in that diagram indicates a call from the BPA into the BSL to process security on that single bundle at the specific location.
A more detailed view of the BSL processing sequence at each of those interaction points is described later in <<sec-workflow-bundle>>.

[#fig-bsl-interaction-points]
.Interaction Points from the BPA into BSL
graphviz::static/bsl-interaction-points.gv[format=svg,width=140mm]

In addition to the bundle-related calls into the BSL and from the BSL, there are also other calls related to:

. Heap memory management callbacks used by the BSL.
If not provided, the standard `libc` functions for heap allocation are used.
. Logging callbacks related to determining if logging is enabled at a specific severity level and to record a log event.
. Telemetry counter access from each BSL instance through a synchronous call from the BPA.

These secondary callbacks are registered by the BPA as part of the initialization of <<sec-workflow-bpa>> and explained in more detail in <<sec-api-secondary>>.

=== Calling Directions

Separate from the structural aspects of the BSL and its external APIs, there are different directions that calls are being made for different interactions between the same entities.
For the factory configuration, using the dynamic backend, these interactions take two forms:

Frontend API::
These are calls into the BSL based on functions declared in its library headers.
These functions are all declared by the BSL frontend library and defined by its backend library.
The portion of the frontend API used by the BPA to initiate security processing is called its **Service API**.

Callback API::
Function calls from the BSL backend into its environment, either to its host BPA or to one of its registered PP or SC instances.
The signature of these callback functions is declared by the BSL, but their definitions are made outside the BSL.
The specific callback function (pointers) registered to the BSL are determined by the host BPA at the time of BSL context initialization (see <<sec-workflow-bpa>>).

The initiating calls are directed from the BPA into the BSL, and then into PPs (to inform what security operations need to be done) and SCs (to actually execute the security operations).
This is depicted in <<fig-calls-service>>, where the BPA initiates the sequence using the frontend API and the BSL calls into each PP and necessary SC based on callbacks injected into the BPA at their times of registration.

[#fig-calls-service]
.Calls Directed From the BPA
[graphviz,format=svg,width=80mm]
----
digraph figure {
    rankdir=TB;
    node [shape=box, fontname=Helvetica, fontsize=12];

    bpa [ label="BP Agent" ];
    bsl [ label="BSL" ];
    pp [ label="Policy Provider(s)" ];
    sc [ label="Security Context(s)" ];

    bpa -> bsl [ label="BSL\nFrontend API" ];
    bsl -> pp [ label="PP\nCallback API"; ]
    bsl -> sc [ label="SC\nCallback API"; ]
}
----

As part of normal PP and SC processing, they will need to obtain data from the bundle, access its various blocks, and obtain some data from the BPA itself.
Some of these calls will originate from the BSL itself and some will originate from the PP and SC instances, passing through the BSL based on its own frontend API.
This is depicted in <<fig-calls-callback>>, which elides the ultimate source of each of these calls (which is always the BPA).

[#fig-calls-callback]
.Calls Directed To the BPA
[graphviz,format=svg,width=100mm]
----
digraph figure {
    rankdir=TB;
    node [shape=box, fontname=Helvetica, fontsize=12];

    bpa [ label="BP Agent" ];
    bsl [ label="BSL" ];
    pp [ label="Policy Provider(s)" ];
    sc [ label="Security Context(s)" ];

    bpa -> bsl [ label="BPA\nCallback API"; dir=back; ];
    bsl -> pp [ label="BSL\nFrontend API"; dir=back; ]
    bsl -> sc [ label="BSL\nFrontend API"; dir=back; ]
}
----

[#sec-api]
== API Overview

The following section provides an overview of the BSL frontend, dynamic-backend, and crypto APIs and references to specific sections and structures from the online <<bsl-main-api>> for more detailed C-language documentation.
This implementation corresponds to the header-only library `bsl_front` and shared libraries `bsl_dynamic` and `bsl_crypto` as explained in the <<bsl-product-guide>>.

The information model for how the BSL operates is built upon the BPSec terminology listed in <<list-terms-bpsec>> with its own additional terms needed for internal logic.

[#sec-api-bundle]
=== Bundle Interactions

All of the discussion in this subsection is at the level of logical entities and information models.
It does not map one-for-one with the actual APIs of the BSL, but is useful for explaining terminology and framing explanations at a higher level than the C-language details.

NOTE: This document uses UML diagrams to depict the logical structure and associations within the BSL.
Because the implementation is based in the C language, there is no such concept as an abstract class, inheritance, or virtual function override.
The BSL uses the concept of a "descriptor" struct to implement this behavior, which is simply a C struct containing a set of callback function pointers and some user data pointer used as a "self" context to each of the callbacks.

The BSL proper is embodied as a "BSL Context" state, for which a single process can have any number of instances.
One BPA option is to have a single BSL Context for all of its security processing, which will save on memory use but will act as a bottleneck if the BPA performs its own bundle processing concurrently at each of the interaction points.
Another BPA option is to use a separate BSL Context for each interaction point and operate them independently and possibly concurrently.

Because the function of the BSL is perform security processing on individual bundles, all of the processing of the BSL Context operates on a single "Bundle Context" at a time.
The purpose of a Bundle Context is to both relate back to some form of BPA-specific _handle_ used to identify the bundle within the BPA, as well as keeping BSL-specific state derived from the BPA-supplied bundle data such as an efficient look-up table for block types or block numbers.

[#fig-bpa-associations]
.BPA and Bundle Context Associations 
plantuml::static/bpa-associations.puml[format=svg,scale=60]

Each BSL Context instance is associated with one or more Policy Provider instances and one or more Security Context instances, as depicted in <<fig-bsl-breakdown>>.
The Policy Providers are used to control _what_ the BSL needs to do for a specific bundle, as discussed in more detail in <<sec-api-pp>>.
The Security Contexts are used to validate and actually execute each security operation, as discussed in more detail in <<sec-api-sc>>.

[#fig-bsl-breakdown]
.BSL Structure Breakdown 
plantuml::static/bsl-breakdown.puml[format=svg,scale=60]

In addition to the externally-visible information about security operations and their _target_, _parameters_, and _results_ the BSL adds the notion of a security Action which is an ordered sequence of specific operations.
This is necessary because some policies require, for example, some operations to be accepted before others are sourced which would refer to the same target block.
The data-use relationships of security operations between PP and SC are depicted in <<fig-secop-assoctaions>>.

[#fig-secop-assoctaions]
.Security Operation Associations 
plantuml::static/secop-associations.puml[format=svg,scale=60]

Another internal information item is the security Option, which is used to communicate configuration of individual security operations between a Policy Provider and an associated Security Context, as depicted in <<fig-secop-in-out>>.
Some options are converted by the SC into Parameters or Results that get encoded into the ASB when acting as the Source role.
Some options, like key identifiers for the default security contexts, do not have representation in the ASB but are necessary for correct processing of the security operation.
A key distinction from the point of view of the SC is that options are internal to the BSL and implicitly trusted, while Parameters and Results (when used as verifier or acceptor role) are untrusted input coming from outside the BPA.

Options are also used to define how operations behave for the source role, but are also used to constrain acceptable behaviors for verifier or acceptor role.
For example, an option can restrict that verification _must_ use a specific security algorithm/strength and if the received operation uses a different algorithm/strength it will be treated as a failure during execution.

[#fig-secop-in-out]
.Logical Relationship between Options and Parameters
[graphviz,format=svg,width=80mm]
----
digraph figure {
    node [shape=rectangle];
    
    sc [label="Security Context\n(execute)"]
    policy [label="Policy Provider"]
    asbin [label="ASB (input)"]
    asbout [label="ASB (output)"]
    
    { rank=same; policy; sc; }
    
    policy -> sc [label="Options"]
    asbin -> sc [label="Parameters\n and Results", style=dashed]
    sc -> asbout [label="Parameters\n and Results", style=dashed]
}
----

The internal representation of Options, Parameters, and Results within the BSL takes the form of a _variant_ capable of holding a value with one of the following types:

Int64::
Used to convey signed and unsigned integer values.
This is limited to 63-bits of magnitude, but currently there are no code points or flags that require all 64 bits of unsigned integer.

Byte String::
Used to convey byte string values from configuration or from ASB content.
For example, authentication tags of default security contexts or COSE messages of the COSE context.

Text String::
Used to convey text string values from configuration.
There are currently no security contexts which use text strings as a parameter or result.

Raw::
Used to convey other context-specific byte-string-encoded values.
For example, the AAD Scope option and parameter for the COSE context as a CBOR-encoded map.

[#sec-api-secondary]
=== Secondary Interactions

Separately from the bundle-related interactions described in <<sec-api-bundle>>, the BPA and BSL interact through several other interfaces related to infrastructure needs described below and depicted in <<fig-secondary-assoctaions>>.
For the dynamic backend, the callbacks are registered during initialization of the process in <<sec-workflow-bpa>>.

Heap Allocation::
For the dynamic backend, heap memory management callbacks are contained in a memory descriptors struct.
As a safeguard for consistency, the custom memory functions will only be used when all of the callback pointers are non-NULL.
If not provided, the standard `libc` functions for heap allocation are used.

Event Logging::
There are two callbacks in the dynamic backend related to logging.
One is a function to determine if logging is enabled at a specific severity level, which is useful to avoid resource-intensive processing that is only actually recorded at low severity.
The other is a function to actually process and record log events, each event includes a human-readable text message as well as metadata about the event such as its severity and the timestamp at which the event occurred.
The event interface is similar to the POSIX `syslog` API but tailored to BSL use.

Telemetry Counters::
Telemetry from each BSL context is accessed through calls into the BSL context via the synchronous function `BSL_LibCtx_AccumulateTlmCounters()`.
It is up to the host BPA to determine if, when, and how often to collect BSL telemetry and either log or aggregate the values itself.
The content of the obtained `BSL_TlmCounters_t` struct is designed to be aggregated across multiple BSL contexts to make it easy for a BPA to report on statistics at individual interaction points as well as aggregated to whole-node statistics.

[#fig-secondary-assoctaions]
.Secondary Associations with BPA
plantuml::static/secondary-associations.puml[format=svg,scale=60]

[#sec-api-pp]
=== Policy Provider Interface

Policy Providers need to be registered with a library context via the dynamic backend before they can be used.
Policy Providers must implement the function headers of the dynamic backend `BSL_PolicyDesc_t` struct defined in the `BPSecLib_Private.h` header file.

Policy Providers must inspect each bundle to produce an Action Set, containing Security Operations.
Policy Providers also must finalize over a bundle after each Security Operation has been executed by the security context.

The BSL includes a simple rule-based example PP that may be utilized by any BPA (see <<sec-samplepp>>), and is used by the Mock BPA for BSL testing (see <<sec-mockbpa>>).
This policy provider's data is mutex-protected and may be re-used among multiple threads / BSL contexts (see the Mock BPA for an example).

[#sec-api-sc]
=== Security Context Interface

Security Contexts need to be registered with a library context via the dynamic backend before they can be used.
Security Contexts must implement the function headers of the dynamic backend `BSL_SecCtxDesc_t` struct defined in the `SecurityContext.h` header file.

Security Contexts operate in the context of a single Security Operation over a bundle.
Security Contexts must validate Security Operations for consistency, and process Security Operations on bundles to produce security outcomes.

The BSL includes its own context implementations, as explained in <<sec-defaultsc>> and <<sec-cosesc>>, which are also used by the Mock BPA for BSL testing (see <<sec-mockbpa>>).

[#sec-api-crypto]
=== Cryptographic Processing

Both of the default contexts and the COSE context use a BSL "crypto" library for abstracting cryptographic processing.
It is expected that alternative and/or future contexts will also use this library for abstracting such processing, and the frontend API of that library will evolve as those needs change.

The BSL backend cryptographic interface utilizes OpenSSL to perform AES key wrap/unwrap, HKDF derivation, HMAC integrity, and AES-GCM encryption operations through its "EVP" primitives APIs <<OpenSSL>>.

[#sec-api-crypto-keystore]
==== Key Store Interface

Part of the software-only cryptographic API is the need for an in-memory symmetric key store to provide key material to OpenSSL APIs.

The crypto library reads key material and updates telemetry counters in the key store.
The implementation of the key store is delegated to the host BPA through callbacks (registered during startup <<sec-workflow-bpa>>).

[#sec-api-preprocessor]
=== Preprocessor Define Directives

The BSL library frontend and its dynamic backend do not rely on any externally configured preprocessor defines to operate normally.

The dynamic backend does use defines to configure how the M*LIB library allocates memory, routing all allocation calls to the host heap allocation callbacks (see <<sec-api-secondary>>).


[#sec-workflow]
== Workflows
A simple BPA that utilizes the example policy provider, default security contexts, and dynamic backend could operate with the following workflow:

[#sec-workflow-bpa]
=== Initialization of BPA Callbacks

The following steps are not thread safe and must be performed before any BSL context instances are initialized (in <<sec-workflow-bslctx>>).

. *Set Host Descriptors*:
The BSL backend relies on host-specific information from the BPA, such as EID registering and encoding information.
The function-pointer fields of a `BSL_HostDescriptors_t` struct should be set with host-implemented functions and initialized with `BSL_HostDescriptors_Set()` for successful BSL operation.
See the Mock BPA for a simple example of implementing host descriptors.

. *Set Key Store Descriptors*:
The BSL crypto interface relies on a host-specific cryptographic key store to access key material needed by security contexts.
The function-pointer fields of a `BSL_KeyStore_Descriptors_t` struct should be set with host-implemented functions and initialized with `BSL_KeyStore_Init()` for successful BSL operation.


[#sec-workflow-bslctx]
=== Initialization of a BSL Context

The following steps contain BSL initialization instructions to be performed once (per-thread).
The correct operation relies on the host BPA configuration from <<sec-workflow-bpa>> to be in-place.

. *Initialize the Library Context*:
Each runtime instance of the BSL is isolated for thread safety within a host-specific struct referenced by a `BSL_LibCtx_t` pointer.
Each instance should be initialized using `BSL_LibCtx_Init()`.

. *Initialize EIDs*:
BPAs can register one or more nodes, each of which has a unique endpoint ID (EID).
Each EID must be registered with the host using `BSL_HostEID_Init()`.

. *Register Example Policy Provider with the Library Context*:
Register the example Policy Provider with the Library Context.

. *Register Default Security Contexts with the Library Context*:
Register the needed Default Security Contexts (BIB-HMAC-SHA2, BCB-AES-GCM, and COSE) with the Library Context.

[#sec-workflow-bundle]
=== Single-Bundle Workflow

The following steps should be performed for each bundle being processed, their entity relationships are depicted in <<fig-bsl-bundle-workflow>>.
All of these actions operate within a BSL library context, initialized in <<sec-workflow-bslctx>>.

. *Initialize Bundle Context for each Bundle*:
For each bundle being processed by BPA at one of the four points of interaction (APPIN, APPOUT, CLIN, CLOUT), initialize a bundle context.
The bundle context will keep track of a bundle's state throughout its interaction with the BSL.
The context must utilize the host-specific struct `BSL_BundleCtx_t`.

. *Inspect Bundles with Policy Providers*:
Utilize the example Policy Provider's inspection function to produce an Action Set that contains Security Operations (Security Operations) to perform on the current bundle context.

. *Validate Security Operations with Security Contexts*:
For each Security Operation contained within the Action Set, utilize the validate function from the relevant Default Security Context to ensure validity and feasibility of the operation.

. *Execute Security Operations with Security Contexts*:
For each Security Operation contained within the Action Set, utilize the execute function from the relevant Default Security Context to perform the operations on the bundle context.
The Security Context will produce Security Outcomes which will be returned to the BPA.

. *Finalize Bundles with Policy Providers*:
Utilize the example Policy Provider's finalize function to verify successful security operations, handle unsuccessful operations, and verify bundle consistency.

. *Free Bundle Context*:
The bundle has now completed the required BSL interactions, and the bundle context resources can be released.
The bundle can now be forwarded within the BPA.

[#fig-bsl-bundle-workflow]
.Sequence Diagram of Per-Bundle Workflow
plantuml::static/bundle-workflow.puml[format=svg,width=110mm]

The BSL Frontend API consists of two primary functions for per-bundle operation: 

1. `BSL_API_QuerySecurity` covers steps 1 through 10 above.
The function first utilizes the policy providers to query on a bundle.
Next, each security operation in the resulting Action Set is validated using the security context associated with that security operation.

2. `BSL_API_ApplySecurity` covers steps 11 through 25 above.
The function first executes each security operation with its associated security context.
Next, the results of each action are finalized using the policy provider which was the source of the action.

=== De-initialization of a BSL Context

Before joining or termination of an associated work thread, each `BSL_LibCtx_t` instance should be de-initialized with `BSL_LibCtx_Deinit()` to free its resources.

Each BSL Context is independent of all others, so there is no need to coordinate activities of one with any other.


[#sec-defaultsc]
== Default Security Contexts

The BSL source and default build includes implementations of the two Default Security Contexts <<RFC9173>> as an working example of how to use the BSL frontend and crypto APIs.

This implementation corresponds to the shared library `bsl_default_sc` as explained in the <<bsl-product-guide>> and the API Docs subsection on https://nasa-ammos.github.io/BSL/html/examples-and-mocks.html#default-scs[Default Contexts].

The default security contexts are:

 * Context ID 1 "BIB-HMAC-SHA2" for BIB use
 * Context ID 2 "BCB-AES-GCM" for BCB use

[#sec-defaultsc-preprocessor]
=== Preprocessor Define Directives

The following are preprocessor define directives related to options of the BIB-HMAC-SHA2 context.
Their enumerated values are not part of the API.

`BSLX_BIB_OPT_KEY_ID`::
The ID of an option used to convey the mandatory key ID as a text string.
Valid values must be present in the BPA key store to be usable in any BPSec role.
`BSLX_BIB_OPT_USE_KEY_WRAP`::
The ID of an option used to convey the integer value 0, to skip key wrap and use as a content key, or 1, to perform key wrap of a random content key.
`BSLX_BIB_OPT_SHA_VARIANT`::
The ID of an option used to convey the integer SHA Variant.
Valid values are defined by Section 3.3.1 of <<RFC9173>> and are used directly by this option.
`BSLX_BIB_OPT_SCOPE`::
The ID of an option used to convey the integer IPPT Scope.
Valid values are defined by Section 3.3.3 of <<RFC9173>> and are used directly by this option.

The following are preprocessor define directives related to options of the BCB-AES-GCM context.
Their enumerated values are not part of the API.

`BSLX_BCB_OPT_KEY_ID`:: 
The ID of an option used to convey the mandatory key ID as a text string.
Valid values must be present in the BPA key store to be usable in any BPSec role.
`BSLX_BCB_OPT_USE_KEY_WRAP`::
The ID of an option used to convey the integer value 0, to skip key wrap and use as a content key, or 1, to perform key wrap of a random content key.
`BSLX_BCB_OPT_AES_VARIANT`::
The ID of an option used to convey the integer AES Variant.
Valid values are defined by Section 4.3.2 of <<RFC9173>> and are used directly by this option.
`BSLX_BCB_OPT_SCOPE`::
The ID of an option used to convey the integer AAD Scope.
Valid values are defined by Section 4.3.4 of <<RFC9173>> and are used directly by this option.


[#sec-cosesc]
== COSE Context

The BSL source and default build includes an implementation of the COSE Context <<draft-ietf-dtn-bpsec-cose>> as a more complex and full-featured use of the crypto APIs.
This implementation is limited to only the symmetric key COSE algorithms listed in Section 3.2.2 and related COSE header parameters listed in Section 3.3 with key identifier considerations discussed in Section 3.4 of that specification.

This implementation corresponds to the shared library `bsl_cose_sc` as explained in the <<bsl-product-guide>> and the API Docs subsection on https://nasa-ammos.github.io/BSL/html/examples-and-mocks.html#cose-sc[COSE Context].

The COSE context has Context ID 3 for both BIB and BCB use.

[#sec-cosesc-preprocessor]
=== Preprocessor Define Directives

The following are preprocessor define directives related to options of the COSE context.
Their enumerated values are not part of the API.

`BSLX_COSESC_OPTION_KEY_ID`::
The ID of an option used to convey a key ID as a byte string (which may contain encoded UTF8 text, but that is not inspected by the implementation).
Valid values must be present in the BPA key store to be usable in any BPSec role.
This is required for source role and an optional filter for verifier/acceptor.
If the COSE Key algorithm is different than `BSLX_COSESC_OPTION_TGT_ALG` option,
the key will be used for the recipient layer, otherwise it will be used
for a single-layer message.

`BSLX_COSESC_OPTION_KEY_ALG`::
The ID of an option used to convey the integer COSE algorithm associated with the top COSE layer (recipient).
This is optional for source role and optional filter for verifier/acceptor.
If not provided the COSE Key must contain an algorithm parameter.
Valid values are taken from the subset of the COSE algorithms registry implemented by this plugin.

`BSLX_COSESC_OPTION_TGT_ALG`::
The ID of an option used to convey the integer COSE algorithm associated with the lowest COSE layer (content).
This is required for source role and optional filter for verifier/acceptor.
Valid values are taken from the subset of the COSE algorithms registry implemented by this plugin.

`BSLX_COSESC_OPTION_AAD_SCOPE`::
The ID of an option used to convey the a byte string of the CBOR-encoded AAD Scope parameter.
This is optional for source role, optional exact-match for verifier/acceptor.
Valid values follow the structure defined in Section 2.2.2 of <<draft-ietf-dtn-bpsec-cose>>.
A helper function `BSLX_CoseSc_SetAadScope()` is provided to simplify value encoding.

`BSLX_COSESC_OPTION_IV_COUNTER_OFFSET`::
The ID of an option used to convey the integer offset to add to the key use counter and treated as a partial IV according to COSE processing rules.

`BSLX_COSESC_OPTION_IV_BASE`::
The ID of an option used to convey the byte string treated as a base IV according to COSE processing rules.
This is optional for source role and unused for verifier/acceptor.
Valid values must match the IV length of the content encryption algorithm.

`BSLX_COSESC_OPTION_SALT_LENGTH`::
The ID of an option used to convey the integer length (in bytes) of salt for KDF sources.
This is optional for source role and unused for verifier/acceptor.
When not present, the default salt length for the KDF algorithm will be used.

`BSLX_COSESC_OPTION_SALT_COUNTER_OFFSET`::
`BSLX_COSESC_OPTION_SALT_BASE`::
These IDs of options are used to control deterministic recipient KDF salt generation using the same algorithm defined by COSE for partial and base IV combination.
If these are present, the `BSLX_COSESC_OPTION_SALT_LENGTH` option is ignored as the base byte string defines the length.

[#sec-samplepp]
== Sample Policy Provider

The BSL source and default build includes a policy provider which has heritage in the ION BPA and is used to configure options for the Security Context implementations of <<sec-defaultsc>> and <<sec-cosesc>>.
Alternative SC implementations can have other internal options that the example policy provider is unaware of and cannot configure.

This implementation corresponds to the shared library `bsl_sample_pp` as explained in the <<bsl-product-guide>> and the API Docs subsection on https://nasa-ammos.github.io/BSL/html/examples-and-mocks.html#example-pps[Example Policy Providers].

[#sec-samplepp-json]
=== JSON-Defined Policy Provider Rules

The sample policy provider has the option to parse and load JSON-encoded ION-like policy rules into the sample policy provider from a file.
The policy syntax has a formal definition in the form of a JSON Schema <<json-schema>> definition file managed in the BSL source tree, distributed as part of BSL software packaging, and included in <<app-samplepp-schema>> as a reference snapshot.
The schema file is named `config-schema.json` in both source and installed paths.

The schema is summarized here with a full explanation for the semantics of each structure or parameter.
The full configuration is a JSON object with the following properties:

`policyrule_set`::
An array of individual policy rule definitions, each being an object with a single property `policyrule` having the following structure.

Each policy rule has the following properties:

`desc`::
A human-friendly text description of each rule which is not used by the policy provider for any data processing.
`filter`::
A part of the rule which defines when the rule applies to a bundle being processed by the BPA.
+
The value is an object with the following properties:

`rule_id`:::
A unique integer identifier for each rule, used in diagnostics about the rule instance.
The value is an integer number or integer-as-text (decimal or hexadecimal).
`loc`:::
The name of the interaction point at which this rule is applied.
The value is one of the text strings "appin", "appout", "clin", or "clout".
`role`:::
The role that this node is acting as for the associated security operation.
The value is one of the text strings "source", "verifier", or "acceptor" or the shortened form which is the first letter of each of those names.
Other rule properties have different effects depending on whether this node is a security source or not.
`src`:::
An EID Pattern used to match the bundle Source EID from the primary block.
The value is the text form of the pattern and may contain multiple pattern items.
If not present, a default match-all rule of "\*:**" is used.
`dest`:::
An EID Pattern used to match the bundle Destination EID from the primary block.
The value is the text form of the pattern and may contain multiple pattern items.
If not present, a default match-all rule of "\*:**" is used.
`sec_src`:::
An EID Pattern used to match the Security Source EID from an associated BIB or BCB block content.
The value is the text form of the pattern and may contain multiple pattern items.
If not present, a default match-all rule of "\*:**" is used.
+
This property is only meaningful for verifier or acceptor roles, because the source role will always use the BPA-provided Security Source EID.
`tgt`:::
The target block _type code_ to which this rule applies.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
CAUTION: This number is not the unique block number within a bundle. The actual security operation will target a specific block by its block number which is unique to that enveloping bundle by looking-up this block type value.

`spec`::
A part of the rule which defines how to construct the security operation when the rule applies to a bundle.
+
The value is an object with the following properties:

`svc`:::
The security service that must apply to the matched target block.
The value is a text string starting with either "bib" or "bcb" to indicate an integrity service or confidentiality service respectively.
+
For source role this will cause an operation to be added to a new BIB or BCB respectively, for verifier and acceptor roles this will search existing BIB or BCB in the bundle.
`sc_id`:::
The specific security context that must have an operation on the target block.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
For source role this will cause an operation to be added to a new BIB or BCB respectively, for verifier and acceptor roles this will search existing BIB or BCB for the context ID.
+
NOTE: For the operation to be valid, this must be one of the security context ID actually registered with the BSL instance processing this policy configuration.
`sc_parms`:::
These are options specific to the `sc_id` sibling value and defined by each context implementation.
The structure of parameters is as a logical ID--value pairing, and the encoding of parameters is either:
 * An array-of-objects each with an `id` and `value` property (the form inherited from ION syntax, see <<sec-samplepp-json-fromion>>), or
 * A single object with properties named for each parameter, which is a more concise syntax and more amenable to JSON Schema specification.

`policy_action_on_fail`::
Determines how the policy provider reacts when a created security operation fails to execute.
The value is one of the following text strings:
"nothing":::
The operation is discretionary and if it fails there will be no side-effects.
+
CAUTION: For source role the failure of an operation is due to local mis-alignment between policy and key store (_i.e._, using the wrong key name).
It is recommended to not use this action for source role.
"drop_block":::
If the operation fails the target block will be dropped, along with any follow-on effects that the BPA will apply (based on the target block flags).
"delete_bundle":::
If the operation fails the entire bundle will be deleted, along with any follow-on effects that the BPA will apply (such as status reporting).

The specific parameters for each of the BSL-implemented contexts are defined below and are present in the schema file as conditional overrides of the object-form encoding.

==== BIB-HMAC-SHA2 Context Options

The Context ID 1 "BIB-HMAC-SHA2" has the following options (derived from the internal enumerations of <<sec-defaultsc-preprocessor>>) in policy syntax:

`key_name`::
The text name of the associated key in the local BPA key store.
The value must match the key store name exactly, in a case-sensitive manner.
+
This is a mandatory input and behaves the same for all roles.
This functions the same for all roles because this context does not include a key identifier in its security block data.
`key_wrap`::
Determine whether the associated key must be used as a key-encryption-key with key wrapping (if true) or used as a direct content key (if false).
The value is either a JSON boolean, a number (0 is false, others are true), or text ("0" is false, others are true).
+
For source role this will control how the key is used in the operation, for verifier and acceptor roles this will act as an mandatory constraint on the use of key wrapping.
`sha_variant`::
The specific HMAC-SHA2 code point to use, interpreted as defined in <<RFC9173>>.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
For source role this will cause an operation to be added using the specific code point, for verifier and acceptor roles this will act as an optional constraint on valid code points.
`scope_flags`::
The specific IPPT flags to use, interpreted as defined in <<RFC9173>>.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
For source role this will cause an operation to be added using these flags, for verifier and acceptor roles this will act as an optional constraint on valid flags.

==== BCB-AES-GCM Context Options

The Context ID 2 "BCB-AES-GCM" has the following options (derived from the internal enumerations of <<sec-defaultsc-preprocessor>>) in policy syntax:

`key_name`::
The text name of the associated key in the local BPA key store.
The value must match the key store name exactly, in a case-sensitive manner.
+
This is a mandatory input and behaves the same for all roles.
This functions the same for all roles because this context does not include a key identifier in its security block data.
`key_wrap`::
Determine whether the associated key must be used as a key-encryption-key with key wrapping (if true) or used as a direct content key (if false).
The value is either a JSON boolean, a number (0 is false, others are true), or text ("0" is false, others are true).
+
For source role this will control how the key is used in the operation, for verifier and acceptor roles this will act as an mandatory constraint on the use of key wrapping.
`aes_variant`::
The specific AES-GCM code point to use, interpreted as defined in <<RFC9173>>.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
For source role this will cause an operation to be added using the specific code point, for verifier and acceptor roles this will act as an optional constraint on valid code points.
`aad_scope`::
The specific AAD flags to use, interpreted as defined in <<RFC9173>>.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
For source role this will cause an operation to be added using these flags, for verifier and acceptor roles this will act as an optional constraint on valid flags.

==== COSE Context Options

The Context ID 3 "COSE" has the following options (derived from the internal enumerations of <<sec-cosesc-preprocessor>>) in policy syntax:

`key_name`::
The text name of the associated key in the local BPA key store.
The value will be converted to a byte string internally using UTF-8 encoding without null termination.
+
For source role this will cause an operation to be added using the specific key, for verifier and acceptor roles this will act as an optional constraint on the allowed key.
`key_id`::
The raw Key ID byte string of the associated key in the local BPA key store.
The value is a hexadecimal encoding of the bytes, with optional "0x" prefix.
+
Only one of `key_name` and `key_id` can be supplied for a single operation and the role-specific logic is identical between the two.
`target_alg`::
The specific target (COSE content layer 0) algorithm code point to use, interpreted as defined in <<RFC9052>> and the IANA "COSE Algorithms" registry.
The value is an integer number or integer-as-text (decimal or hexadecimal).
+
The key store can include a key algorithm constraint, and if this target algorithm is different from the key algorithm it will result in a two-layer COSE message where the key algorithm applies to a single recipient and this target algorithm applies to the content layer.
+
For source role this will cause an operation to be added using the specific algorithm, for verifier and acceptor roles this will act as an optional constraint on the allowed algorithm.
`aad_scope`::
The specific AAD Scope to allow.
The value is a JSON object itself having integer-as-text keys (representing AAD Scope block numbers or special keys) and integer-number or integer-as-text values (representing AAD Scope flags).
+
For source role this will cause an operation to be added using the specific scope, for verifier and acceptor roles this will act as an optional constraint on the allowed scope.
`iv_counter_offset`::
A source of Partial IV for COSE content algorithms which make use of an IV (_e.g._, encryption).
The value is an integer number or integer-as-text (decimal or hexadecimal) representing an offset from the key use counter to the big-endian integer encoded as Partial IV bytes.
+
This option is only applicable to the source role; the Partial IV is conveyed within a COSE message.
`iv_base`::
A supplemental Base IV when the key store does not already provide one for the used key.
The value is a hexadecimal encoding of the bytes, with optional "0x" prefix.
+
This option is only applicable if the key store itself does not provide a Base IV key parameter and behaves identically for all roles.
`salt_length`::
The length of salt to use for COSE recipient algorithms which use a salt (_e.g._, key derivation).
The value is an integer number or integer-as-text (decimal or hexadecimal) representing the length in bytes.
If not provided, the algorithm-default salt length is used.
+
This option is only applicable to the source role, the salt value is conveyed within a COSE message.
Only one of `salt_length` or the pair of `salt_counter_offset` and `salt_base` apply to a single operation.
`salt_counter_offset`::
A source of unique salt for COSE content algorithms which use a salt.
The value is an integer number or integer-as-text (decimal or hexadecimal) representing an offset from the key use counter to the big-endian integer encoded as Partial IV bytes.
+
This option is only applicable to the source role, the salt value is conveyed within a COSE message.
`salt_base`::
A full-length base byte string combined by XOR with the byte string derived from `salt_counter_offset` to produce a full unique salt.
The value is a hexadecimal encoding of the bytes, with optional "0x" prefix.
+
This option is only applicable to the source role, the salt value is conveyed within a COSE message.


[#sec-samplepp-json-fromion]
==== Extensions or Deviations from ION Syntax

This policy syntax is derived from the original ION BPSec policy syntax <<ION-BPSec-Policy-Manual>> with some notable differences/modifications mentioned as follows:

New property `loc`::
An new property of `filter` that specifies the interaction point (one of "appin", "appout", "clin", "clout") where the policy rule should be applied.
 
New property `policy_action_on_fail`::
A new property of each `policyrule` to control its response to failure of an operation execution.
A full policy event set implementation does not exist yet within BSL.
For now, a temporary `policy_action_on_fail` attribute should be set to "delete_bundle", "drop_block", or "nothing".

Concise form of context options::
The object-property form of context options make the policy configuration more compact, easier to read, and more amenable to JSON Schema specification.
The legacy form is still fully supported and the policy value handling and checking is identical between the two forms.

New `key_wrap` context option::
An extra security context 1 and 2 parameter ID `key_wrap` will be parsed.
When the value is set to 0 (or "0"), key wrapping will be skipped.
For all other values, key wrapping will be enabled.
Decision to key wrap is a required parameter for security operations when executed within the implementations of the Default Security Contexts.

Allowance for JSON numbers and booleans as values::
For specific policy configuration values and for some context options, the more "natural" form of value input is to use JSON numbers or JSON boolean values.
There is backward compatibility provided for text values to be interpreted as integers, which allows for hexadecimal number input that JSON does not support for its number encoding.


=== Steps to initialize policy provider from JSON

This procedure is how a BPA making use of the example policy provider initializes and registers with each instance of the BSL.

. Initialize policy provider data with `BSLP_PolicyProvider_Init()`.

. Initialize policy rules from JSON by calling `BSLP_RegisterPolicyFromJSON()`.

. Register the policy with BSL by calling `BSL_API_RegisterPolicyProvider()`, the policy where the `user_data` of the policy provider descriptor is set to the initialized policy provider.


[#sec-samplepp-preprocessor]
=== Preprocessor Define Directives

The Example PP does not rely on any externally configured preprocessor defines to operate normally.
It does rely on the defines from the Default Security Context to control options of security operations used by the PP.


[#sec-mockbpa]
== The BSL Mock BPA

This is an executable used to provide a test fixture and example BPA integration of specific security context and policy provider instances.
This implementation corresponds to the executable `bsl-mock-bpa` and shared library `bsl_mock_bpa` as explained in the <<bsl-product-guide>> and the API Docs subsection on https://nasa-ammos.github.io/BSL/html/examples-and-mocks.html#mock-bpa[Mock BPA].

The Mock BPA does not provide any of the normal processing required of a real BPA by <<RFC9171>>, it is limited to decoding and encoding BPv7 protocol data unit (PDU) byte strings, processing specific BPv7 primary block fields, providing BSL-required integration callbacks, and calling into the BSL for each bundle being processed at each interaction point.
The Mock BPA communicates with "the outside" at each interaction point using UDP/IP socket binds configured by command options explained in detail in <<bsl-main-api>>.

Users may find it useful to reference the Mock BPA for a working example of library and bundle workflow, and working examples of initializing, registering, and operating the Default Security Context (of <<sec-defaultsc>>) and the Example Policy Provider (of <<sec-samplepp>>).
Exercising of the Mock BPA is part of normal BSL continuous integration (CI) testing and release testing, so it is always in-sync with the BSL APIs.

[#sec-mockbpa-preprocessor]
=== Preprocessor Define Directives

The following are preprocessor define directives that limit certain capabilities within the Mock BPA.

`MOCK_BPA_LOG_QUEUE_SIZE` = 100::
Number of logging events to buffer before output.

`DATA_QUEUE_SIZE` = 100::
Size of the Mock BPA ingress and egress queues for each thread.


[#sec-support]
== Product Support

There are two levels of support for the BSL: troubleshooting by a system administrator, which is detailed in <<sec-troubleshooting>>, and upstream support via the BSL public GitHub project, accessible as described in <<sec-contact>>.
Attempts to troubleshoot should be made before submitting issue tickets to the upstream project.

[#sec-troubleshooting]
=== Troubleshooting

The following provides troubleshooting guidance for the BSL from the perspective of a normal or administrative user.
Each situation consists of an observed state followed by a recommended troubleshooting activity.

[qanda]
Why is BSL writing logs to standard error?::
The host callback for handling log events has not been set and BSL is falling back to default `stderr` logging.
Set the `log_event` (and optionally the `log_enabled_for`) callbacks in the registered `BSL_HostDescriptors_t` struct to handle logging via the BPA.

Why is BSL not using my memory management functions?::
All of the members of the `BSL_DynMemHostDescriptors_t` must non-NULL to be used.
If some but not all members are non-NULL that is treated as an error (along with a log event) and the default `libc` functions are used.


[#sec-contact]
=== Contacting or Contributing

The BSL is hosted on a GitHub repository <<bsl-source>> with submodule references to several other repositories.
There is a https://github.com/NASA-AMMOS/BSL/blob/main/CONTRIBUTING.md[`CONTRIBUTING.md`] document in the BSL repository which describes detailed procedures for submitting tickets to identify defects and suggest enhancements.

Separate from the source for the BSL proper, the BSL Product Guide and User Guide are hosted on a GitHub repository <<bsl-docs>>, with its own https://github.com/NASA-AMMOS/BSL-docs/blob/main/CONTRIBUTING.md[`CONTRIBUTING.md`] document for submitting tickets about either the Product Guide or User Guide.

While the GitHub repositories are the primary means by which users should submit detailed tickets, other inquiries can be made directly via email to the the support address mailto:dtnma-support@jhuapl.edu[,BSL Support].

[appendix]
== Sample Policy Provider Files

[#app-samplepp-schema]
=== Policy Configuration JSON Schema

The full JSON Schema for the Sample Policy Provider configuration described in <<sec-samplepp-json>> is in this section as a snapshot of the working branch of the BSL.
Each release tag and formal release package of the BSL will contain a schema file specific to that version.

.Snapshot of JSON Schema for Sample Policy Provider Configuration
[source,json]
include::https://github.com/NASA-AMMOS/BSL/raw/refs/heads/main/src/bsl/sample_pp/config-schema.json[]

[#app-samplepp-examples]
=== Example Policy Configurations

The policy configuration below can be used to reproduce the example in Appendix A.1 of <<RFC9173>>.
Because the rule omits any "src" or "dest" properties, it will add a BIB targeting the payload of _all_ bundles transmitted from the local node.

[#src-samplepp-config-sc1-source]
.Policy Configuration for BIB-HMAC-SHA2 Source Role
[source,json]
include::https://github.com/NASA-AMMOS/BSL/raw/refs/heads/main/mock-bpa-test/data/default-scs/policy-exA.1-source.json[]

A pairing of configurations can be used to reproduce the example in Appendix A.1 of the COSE Context, where the acceptor configuration omits constraining options to actually allow _any_ BIB referencing a known, algorithm-appropriate key to be accepted.
A more constrained acceptor configuration would include all of the same "sc_parms" options as the source to ensure the actual operation matches the desired options.

[#src-samplepp-config-sc3-source]
.Policy Configuration for COSE Source Role
[source,json]
include::https://github.com/NASA-AMMOS/BSL/raw/refs/heads/main/mock-bpa-test/data/cose-sc/policy-exA.1-source.json[]

[#src-samplepp-config-sc3-accept-any]
.Policy Configuration for COSE Acceptor Role
[source,json]
include::https://github.com/NASA-AMMOS/BSL/raw/refs/heads/main/mock-bpa-test/data/cose-sc/policy-any-bib-accept.json[]
