@startuml
hide circle
skinparam ClassAttributeIconSize 0

!include classes.puml!bpa
!include classes.puml!bsl

class "Bundle Context" as Bundle {
  + location : Processing Location
  - handle : Bundle reference
  + getters()
}

BPA *--> "0..*" Bundle : own
BPA *--> "0..*" BSL : own
BSL --> Bundle : interact

@enduml
