@startuml
autonumber

participant "BPA" as BPA
participant "BSL" as BSL
participant "Policy Provider" as Policy
participant "Security Context" as SC
participant "Crypto Library" as Crypto

activate BPA #dcebff
BPA -> BSL : query security
activate BSL #dcebff

BSL -> BSL : index ASBs

loop each provider
    BSL -> Policy : query

    activate Policy #dcebff
    Policy -> BPA : [as needed]\nget data

    activate BPA #dcebff
    BPA --> Policy
    deactivate BPA
    ||5||

    Policy --> BSL : action set
    deactivate Policy
    ||5||

    loop each action

        loop each secop
            BSL -> SC : validate secop
            activate SC #dcebff
            SC --> BSL
            deactivate SC
        end
    end

    alt any validation failed
        BSL -> BSL : actions ignored
    end
end
BSL --> BPA : action set
deactivate BSL

||20||

BPA -> BSL : apply security
activate BSL #dcebff

loop each action
    loop each secop

        BSL -> SC : run secop
        activate SC #dcebff

        SC -> BPA : [as needed]\nget data
        activate BPA #dcebff
        BPA --> SC
        deactivate BPA

        SC -> Crypto : [as needed]\ncrypto functions
        activate Crypto #dcebff
        Crypto --> SC
        deactivate Crypto

        SC -> BPA : [as needed]\nalter bundle
        activate BPA #dcebff
        BPA --> SC
        deactivate BPA

        SC --> BSL : secop outcome
        deactivate SC
        ||5||
    end
end

loop each action
    BSL -> BSL : lookup action PP

    BSL -> Policy : finalize
    activate Policy #dcebff

    Policy -> BPA : [as needed]\nalter bundle
    activate BPA #dcebff
    BPA --> Policy
    deactivate BPA

    Policy --> BSL
    deactivate Policy
    ||5||
end

BSL --> BPA : outcomes
deactivate BSL
||10||

@enduml