@startuml
hide circle
hide members
skinparam ClassAttributeIconSize 0
skinparam minClassWidth 160

class "BP Agent" as BPA {
}

class "BSL Context" as BSL {
}

BSL --> BPA : memory
BSL --> BPA : logging
BPA --> BSL : telemetry

@enduml
