@startuml
hide circle
skinparam ClassAttributeIconSize 0

class "Policy Provider" as PP {
  + inspect(ctx: Bundle Context {const}) : Security Action [0..*]
  + finalize(ctx: Bundle Context)
}

class "Security Context" as SC {
  + validate(ctx: Bundle Context {const}, op: Security Operation {const}) : bool
  + execute(ctx: Bundle Context, op: Security Operation) :
}

class "Security Operation" as SecOp {
  + role : BPSec Role
  + target : uint64
  + context ID : int16
  + options : Option[0..*]
  + conclusion : bool [0..1]
}

class "Security Action" as Action {
}
Action *--> "*" SecOp : sequence

PP --> Action : creates
SC --> SecOp : reads

@enduml
