@startuml
hide circle
hide members
skinparam ClassAttributeIconSize 0
skinparam minClassWidth 150

!include classes.puml!bpa
!include classes.puml!bsl

BSL --> BPA : memory
BSL --> BPA : logging
BPA --> BSL : telemetry

@enduml
